server:
  port: 18009
spring:
  application:
    name: MK-Gatway
  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

logging:
  level:
    org:
      springframework:
        boot: info
    com.mk.*: debug
