server:
  port: 18009
spring:
  application:
    name: MK-Gatway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
        enabled: true
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
      routes:
        - id: host_route
          uri: http://www.baidu.com
          predicates:
          - Query=chid,wx
          - Path=/baidu/*

logging:
  level:
    org.springframework.*: debug
    com.mk.*: debug

