server:
  port: 8889

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: demo-route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/spring-cloud
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route
#          uri: http://www.google.com
#          predicates:
#            - Path=/foo